/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Restock.java
 *
 * Created on 03.12.2012, 19:24:24
 */

package startframes;
import javax.swing.JOptionPane;
/**
 *
 * @author Admin
 */
public class Restock extends javax.swing.JFrame {

    /** Creates new form Restock */
    public Restock() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLMovieName = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTAdultP = new javax.swing.JTextField();
        jTChildP = new javax.swing.JTextField();
        jTStudentP = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jTTLeft1 = new javax.swing.JTextField();
        jTTLeft2 = new javax.swing.JTextField();
        jTTLeft3 = new javax.swing.JTextField();
        jTTime3 = new javax.swing.JTextField();
        jTTime2 = new javax.swing.JTextField();
        jTTime1 = new javax.swing.JTextField();
        jBSave = new javax.swing.JButton();
        jBCancel = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jT10c = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jT50c = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jT20c = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jT1e = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jT2e = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jT5e = new javax.swing.JTextField();
        jT10e = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jT20e = new javax.swing.JTextField();
        jOptionCheck = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Restock Form");
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setType(java.awt.Window.Type.POPUP);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(-16777216,true)), "Movie"));
        jPanel1.setLayout(null);

        jLMovieName.setFont(new java.awt.Font("Arial Black", 0, 16));
        jLMovieName.setText("jTextField1");
        jLMovieName.setBorder(null);
        jLMovieName.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jLMovieName.setEnabled(false);
        jPanel1.add(jLMovieName);
        jLMovieName.setBounds(70, 10, 290, 23);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Ticket Price"));
        jPanel2.setLayout(null);

        jLabel15.setText("Student");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(40, 60, 50, 20);

        jLabel14.setText("Child");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(40, 40, 50, 20);

        jLabel5.setText("Adult");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(40, 20, 50, 20);
        jPanel2.add(jTAdultP);
        jTAdultP.setBounds(90, 20, 70, 20);
        jPanel2.add(jTChildP);
        jTChildP.setBounds(90, 40, 70, 20);
        jPanel2.add(jTStudentP);
        jTStudentP.setBounds(90, 60, 70, 20);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(240, 50, 200, 90);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Time and tickets left"));
        jPanel4.setLayout(null);
        jPanel4.add(jTTLeft1);
        jTTLeft1.setBounds(130, 20, 70, 20);
        jPanel4.add(jTTLeft2);
        jTTLeft2.setBounds(130, 40, 70, 20);
        jPanel4.add(jTTLeft3);
        jTTLeft3.setBounds(130, 60, 70, 20);
        jPanel4.add(jTTime3);
        jTTime3.setBounds(10, 60, 70, 20);
        jPanel4.add(jTTime2);
        jTTime2.setBounds(10, 40, 70, 20);
        jPanel4.add(jTTime1);
        jTTime1.setBounds(10, 20, 70, 20);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(20, 50, 220, 90);

        jBSave.setText("Save");
        jBSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSaveActionPerformed(evt);
            }
        });

        jBCancel.setText("Cancel");
        jBCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(-16777216,true)), "Bank"));
        jPanel3.setLayout(null);

        jT10c.setFont(new java.awt.Font("Arial", 0, 14));
        jT10c.setText("jTextField1");
        jPanel3.add(jT10c);
        jT10c.setBounds(90, 40, 75, 23);

        jLabel22.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel22.setText("=");
        jPanel3.add(jLabel22);
        jLabel22.setBounds(70, 40, 21, 17);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgCoins/10c.png"))); // NOI18N
        jPanel3.add(jLabel6);
        jLabel6.setBounds(25, 30, 35, 35);

        jT50c.setFont(new java.awt.Font("Arial", 0, 14));
        jT50c.setText("jTextField2");
        jPanel3.add(jT50c);
        jT50c.setBounds(90, 140, 75, 23);

        jLabel20.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel20.setText("=");
        jPanel3.add(jLabel20);
        jLabel20.setBounds(70, 140, 21, 17);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgCoins/50c.png"))); // NOI18N
        jPanel3.add(jLabel8);
        jLabel8.setBounds(12, 130, 48, 48);

        jT20c.setFont(new java.awt.Font("Arial", 0, 14));
        jT20c.setText("jTextField1");
        jPanel3.add(jT20c);
        jT20c.setBounds(90, 90, 75, 23);

        jLabel21.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel21.setText("=");
        jPanel3.add(jLabel21);
        jLabel21.setBounds(70, 90, 21, 17);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgCoins/20c.png"))); // NOI18N
        jPanel3.add(jLabel7);
        jLabel7.setBounds(15, 80, 45, 45);

        jT1e.setFont(new java.awt.Font("Arial", 0, 14));
        jT1e.setText("jTextField3");
        jPanel3.add(jT1e);
        jT1e.setBounds(90, 200, 75, 23);

        jLabel19.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel19.setText("=");
        jPanel3.add(jLabel19);
        jLabel19.setBounds(70, 200, 21, 17);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgCoins/1e.png"))); // NOI18N
        jPanel3.add(jLabel9);
        jLabel9.setBounds(15, 190, 45, 45);

        jT2e.setFont(new java.awt.Font("Arial", 0, 14));
        jT2e.setText("jTextField4");
        jPanel3.add(jT2e);
        jT2e.setBounds(90, 260, 75, 23);

        jLabel18.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel18.setText("=");
        jPanel3.add(jLabel18);
        jLabel18.setBounds(70, 260, 21, 17);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgCoins/2e.png"))); // NOI18N
        jPanel3.add(jLabel10);
        jLabel10.setBounds(8, 240, 55, 58);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgCoins/5e.png"))); // NOI18N
        jPanel3.add(jLabel11);
        jLabel11.setBounds(210, 30, 154, 80);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel1.setText("=");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(370, 60, 21, 17);

        jT5e.setFont(new java.awt.Font("Arial", 0, 14));
        jT5e.setText("jTextField1");
        jPanel3.add(jT5e);
        jT5e.setBounds(390, 60, 75, 23);

        jT10e.setFont(new java.awt.Font("Arial", 0, 14));
        jT10e.setText("jTextField1");
        jPanel3.add(jT10e);
        jT10e.setBounds(390, 160, 75, 23);

        jLabel16.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel16.setText("=");
        jPanel3.add(jLabel16);
        jLabel16.setBounds(370, 160, 21, 17);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgCoins/10e.png"))); // NOI18N
        jPanel3.add(jLabel12);
        jLabel12.setBounds(200, 120, 164, 86);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgCoins/20e.png"))); // NOI18N
        jPanel3.add(jLabel13);
        jLabel13.setBounds(190, 210, 169, 92);

        jLabel17.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel17.setText("=");
        jPanel3.add(jLabel17);
        jLabel17.setBounds(370, 250, 21, 17);

        jT20e.setFont(new java.awt.Font("Arial", 0, 14));
        jT20e.setText("jTextField1");
        jPanel3.add(jT20e);
        jT20e.setBounds(390, 250, 75, 23);

        jOptionCheck.setText("Set JOption Pane to show chage");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jOptionCheck)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                        .addComponent(jBSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBCancel))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBSave, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jBCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jOptionCheck))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jBCancelActionPerformed

    private void jBSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSaveActionPerformed
        // TODO add your handling code here:
        if (startframes.UsersForm.movieIdent!=0){
        startframes.UsersForm.tempMovie.dateTime =  java.util.Arrays.asList(new String[] {jTTime1.getText(),jTTime2.getText(),jTTime3.getText()});

        startframes.UsersForm.tempMovie.price = new double[] {Double.parseDouble(jTAdultP.getText()),
                                                              Double.parseDouble(jTChildP.getText()),
                                                              Double.parseDouble(jTStudentP.getText())};

        startframes.UsersForm.tempMovie.ticketLeft = new int[] {Integer.parseInt(jTTLeft1.getText()),
                                                                Integer.parseInt(jTTLeft2.getText()),
                                                                Integer.parseInt(jTTLeft3.getText())};
        

        /**/
        startframes.UsersForm.saveMStandard(startframes.UsersForm.tempMovie.getMovieID());

        switch(startframes.UsersForm.tempMovie.getMovieID()){
            case 1:
                    startframes.UsersForm.jTButtonMovie1.doClick();
                    break;
            case 2:
                    startframes.UsersForm.jTButtonMovie2.doClick();
                    break;
            case 3:
                    startframes.UsersForm.jTButtonMovie3.doClick();
                    break;
            case 4:
                    startframes.UsersForm.jTButtonMovie4.doClick();
                    break;
            case 5:
                    startframes.UsersForm.jTButtonMovie5.doClick();
                    break;
            case 6:
                    startframes.UsersForm.jTButtonMovie6.doClick();
                    break;
            case 7:
                    startframes.UsersForm.jTButtonMovie7.doClick();
                    break;
            case 8:
                    startframes.UsersForm.jTButtonMovie8.doClick();
                    break;
            case 9:
                    startframes.UsersForm.jTButtonMovie9.doClick();
                    break;
        }
        }

        startframes.UsersForm.bankVariable.bankArray = new int[] {
                                                                    Integer.parseInt(jT10c.getText()),
                                                                    Integer.parseInt(jT20c.getText()),
                                                                    Integer.parseInt(jT50c.getText()),
                                                                    Integer.parseInt(jT1e.getText()),
                                                                    Integer.parseInt(jT2e.getText()),
                                                                    Integer.parseInt(jT5e.getText()),
                                                                    Integer.parseInt(jT10e.getText()),
                                                                    Integer.parseInt(jT20e.getText())
                                                                    };

        if (jOptionCheck.isSelected()) {
        UsersForm.joptionCheckChange = true;
        }
        else {UsersForm.joptionCheckChange = false;}
        //JOptionPane.showMessageDialog(null, "" + jOptionCheck.isSelected());
        setVisible(false);
    }//GEN-LAST:event_jBSaveActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:

    }//GEN-LAST:event_formWindowActivated

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Restock().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCancel;
    private javax.swing.JButton jBSave;
    public javax.swing.JTextField jLMovieName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JCheckBox jOptionCheck;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    public static javax.swing.JTextField jT10c;
    public static javax.swing.JTextField jT10e;
    public static javax.swing.JTextField jT1e;
    public static javax.swing.JTextField jT20c;
    public static javax.swing.JTextField jT20e;
    public static javax.swing.JTextField jT2e;
    public static javax.swing.JTextField jT50c;
    public static javax.swing.JTextField jT5e;
    public javax.swing.JTextField jTAdultP;
    public javax.swing.JTextField jTChildP;
    public javax.swing.JTextField jTStudentP;
    public javax.swing.JTextField jTTLeft1;
    public javax.swing.JTextField jTTLeft2;
    public javax.swing.JTextField jTTLeft3;
    public javax.swing.JTextField jTTime1;
    public javax.swing.JTextField jTTime2;
    public javax.swing.JTextField jTTime3;
    // End of variables declaration//GEN-END:variables

}
